export const REQUESTED_MOVIE_SEARCH = 'REQUESTED_MOVIE_SEARCH';
export const REQUESTED_MOVIE_SEARCH_SUCCEEDED = 'REQUESTED_MOVIE_SEARCH_SUCCEEDED';
export const REQUESTED_MOVIE_SEARCH_FAILED = 'REQUESTED_MOVIE_SEARCH_FAILED';
export const ON_MOVIE_SEARCH_CHANGE = 'ON_MOVIE_SEARCH_CHANGE';
export const CLEAR_MOVIE_SEARCH_FIELD = 'CLEAR_MOVIE_SEARCH_FIELD';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
