export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const REQUESTED_AUTHENTICATION = 'REQUESTED_AUTHENTICATION';
export const REQUESTED_AUTHENTICATION_FAILED = 'REQUESTED_AUTHENTICATION_FAILED';
export const REQUESTED_AUTHENTICATION_SUCCEEDED = 'REQUESTED_AUTHENTICATION_SUCCEEDED';