export const HEADER_HANDLE_MENU = 'HEADER_HANDLE_MENU';
export const HEADER_HANDLE_CLOSE = 'HEADER_HANDLE_CLOSE';
export const IS_AUTH = 'IS_AUTH';
export const LOG_OUT = 'LOG_OUT';
export const SAVE_USERNAME_FROM_FORM = 'SAVE_USERNAME_FROM_FORM';