export const HEADER_HANDLE_MENU = 'HEADER_HANDLE_MENU';
export const HEADER_HANDLE_CLOSE = 'HEADER_HANDLE_CLOSE';
export const IS_AUTH = 'IS_AUTH';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';