export const REQUESTED_MOVIE_INFO = 'REQUESTED_MOVIE_INFO';
export const REQUESTED_MOVIE_INFO_SUCCEEDED = 'REQUESTED_MOVIE_INFO_SUCCEEDED';
export const REQUESTED_MOVIE_INFO_FAILED = 'REQUESTED_MOVIE_INFO_FAILED';