export const ON_MAIL_CHANGE = 'ON_MAIL_CHANGE';
export const ON_PASSWORD_CHANGE = 'ON_PASSWORD_CHANGE'
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const ON_MAIL_CHANGE_REDUX_FORM = 'ON_MAIL_CHANGE_REDUX_FORM';
export const ON_PASSWORD_CHANGE_REDUX_FORM = 'ON_PASSWORD_CHANGE_REDUX_FORM';