export const ON_MAIL_CHANGE = 'ON_MAIL_CHANGE';
export const ON_PASSWORD_CHANGE = 'ON_PASSWORD_CHANGE'
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';
export const SAVE_MAIL_FROM_FORM = 'SAVE_MAIL_FROM_FORM';
export const SAVE_PASSWORD_FROM_FORM = 'SAVE_PASSWORD_FROM_FORM';
export const LOGIN_CLEAR_STATE = 'LOGIN_CLEAR_STATE';
export const LOGIN_REDUX_FORM_SUCCESS = 'LOGIN_REDUX_FORM_SUCCESS';