export const REQUESTED_SEND_COMMENT = 'REQUESTED_SEND_COMMENT';
export const REQUESTED_SEND_COMMENT_SUCCEEDED = 'REQUESTED_SEND_COMMENT_SUCCEEDED';
export const REQUESTED_SEND_COMMENT_FAILED = 'REQUESTED_SEND_COMMENT_FAILED';
export const CLEAR_COMMENT_FIELD = 'CLEAR_COMMENT_FIELD';
export const ON_COMMENT_CHANGE = 'ON_COMMENT_CHANGE';
export const REQUESTED_COMMENTS_SUCCEEDED = 'REQUESTED_COMMENTS_SUCCEEDED';
export const REQUESTED_COMMENTS = 'REQUESTED_COMMENTS';
export const REQUESTED_COMMENTS_FAILED = 'REQUESTED_COMMENTS_FAILED';